
package leilaoonline.web.full.wsclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultaLeilaoWS", targetNamespace = "http://ws.mack.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultaLeilaoWS {


    /**
     * 
     * @param nomeCategoria
     * @return
     *     returns java.util.List<leilaoonline.web.full.wsclient.LeilaoVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "obterLeiloesPorNomeCategoria", targetNamespace = "http://ws.mack.com.br/", className = "leilaoonline.web.full.wsclient.ObterLeiloesPorNomeCategoria")
    @ResponseWrapper(localName = "obterLeiloesPorNomeCategoriaResponse", targetNamespace = "http://ws.mack.com.br/", className = "leilaoonline.web.full.wsclient.ObterLeiloesPorNomeCategoriaResponse")
    @Action(input = "http://ws.mack.com.br/ConsultaLeilaoWS/obterLeiloesPorNomeCategoriaRequest", output = "http://ws.mack.com.br/ConsultaLeilaoWS/obterLeiloesPorNomeCategoriaResponse")
    public List<LeilaoVO> obterLeiloesPorNomeCategoria(
        @WebParam(name = "nomeCategoria", targetNamespace = "")
        String nomeCategoria);

}
